In [1]:
import pandas as pd

In [2]:
import yfinance as yf

In [3]:
data = pd.DataFrame({
    "Company": ["ASML", "NVIDIA", "TSMC"],
    "Revenue": [32.7, 130.5, 90.0]
})

In [4]:
data

  Company  Revenue
0    ASML     32.7
1  NVIDIA    130.5
2    TSMC     90.0

In [5]:
ticker = "ASML.AS"

In [6]:
start_date = "2021-01-01"
end_date = "2026-01-01"

In [7]:
market_data = yf.download(
    ticker,
    start=start_date,
    end=end_date
)

[*********************100%***********************]  1 of 1 completed

In [8]:
market_data

Price            Close        High         Low        Open  Volume
Ticker         ASML.AS     ASML.AS     ASML.AS     ASML.AS ASML.AS
Date
2021-01-04  386.388336  390.906107  382.583897  384.248339  789502
2021-01-05  387.006622  391.904833  381.537740  386.673728  798787
2021-01-06  383.154541  387.291874  379.682996  386.911407  875711
2021-01-07  384.153229  387.862551  380.776801  385.009222  874780
2021-01-08  395.709167  398.610069  393.188733  393.997182  975243
...                ...         ...         ...         ...     ...
2025-12-23  898.916931  899.115995  890.656303  890.755804  258272
2025-12-24  894.736755  896.627769  892.447675  892.746240   59585
2025-12-29  902.499817  907.177541  895.234447  903.793640  380628
2025-12-30  914.044800  919.319654  902.599335  904.092222  402093
2025-12-31  917.030640  917.030640  904.788919  905.585174  156048

[1281 rows x 5 columns]

In [9]:
market_data.head()

Price            Close        High         Low        Open  Volume
Ticker         ASML.AS     ASML.AS     ASML.AS     ASML.AS ASML.AS
Date
2021-01-04  386.388336  390.906107  382.583897  384.248339  789502
2021-01-05  387.006622  391.904833  381.537740  386.673728  798787
2021-01-06  383.154541  387.291874  379.682996  386.911407  875711
2021-01-07  384.153229  387.862551  380.776801  385.009222  874780
2021-01-08  395.709167  398.610069  393.188733  393.997182  975243

In [10]:
market_data.shape

(1281, 5)

In [11]:
market_data.columns

MultiIndex([( 'Close', 'ASML.AS'),
            (  'High', 'ASML.AS'),
            (   'Low', 'ASML.AS'),
            (  'Open', 'ASML.AS'),
            ('Volume', 'ASML.AS')],
           names=['Price', 'Ticker'])

In [12]:
market_data.index

DatetimeIndex(['2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07',
               '2021-01-08', '2021-01-11', '2021-01-12', '2021-01-13',
               '2021-01-14', '2021-01-15',
               ...
               '2025-12-16', '2025-12-17', '2025-12-18', '2025-12-19',
               '2025-12-22', '2025-12-23', '2025-12-24', '2025-12-29',
               '2025-12-30', '2025-12-31'],
              dtype='datetime64[s]', name='Date', length=1281, freq=None)

In [13]:
market_data.dtypes

Price   Ticker
Close   ASML.AS    float64
High    ASML.AS    float64
Low     ASML.AS    float64
Open    ASML.AS    float64
Volume  ASML.AS      int64
dtype: object

In [14]:
market_data.isna().sum()

Price   Ticker
Close   ASML.AS    0
High    ASML.AS    0
Low     ASML.AS    0
Open    ASML.AS    0
Volume  ASML.AS    0
dtype: int64